# Based on the "trust" template v0.1.2
# https://github.com/japaric/trust/tree/v0.1.2

environment:
  global:
  # TODO This is the Rust channel that build jobs will use by default but can be
  # overridden on a case by case basis down below
    #RUST_VERSION: stable
    RUST_VERSION: nightly

    # TODO Update this to match the name of your project.
    CRATE_NAME: VideoAnalysisController

    TARGET: x86_64-pc-windows-gnu

    SECURE_GITHUB_TOKEN:
      secure: yf7Him/R+dJ/gKfZR+Hqc3cwuZVQMWOuR1WZ9XuMwmkWyQD6yDIqUaFIBzcr0oEW
    APPVEYOR_CACHE_SKIP_RESTORE: false
    ENABLE_REMOTE_DESKTOP: false

  # TODO These are all the build jobs. Adjust as necessary. Comment out what you
  # don't need
  #matrix:
    # MinGW
    #- TARGET: i686-pc-windows-gnu
    #- TARGET: x86_64-pc-windows-gnu

    # MSVC
    #- TARGET: i686-pc-windows-msvc
    #- TARGET: x86_64-pc-windows-msvc

    # Testing other channels
    #- TARGET: x86_64-pc-windows-gnu
    #  RUST_VERSION: nightly
    #- TARGET: x86_64-pc-windows-msvc
    #  RUST_VERSION: nightly

install:
  - ps: >-
      If ($Env:TARGET -eq 'x86_64-pc-windows-gnu') {
        $Env:PATH += ';C:\msys64\mingw64\bin'
      } ElseIf ($Env:TARGET -eq 'i686-pc-windows-gnu') {
        $Env:PATH += ';C:\msys64\mingw32\bin'
      }
  - curl -sSf -o rustup-init.exe https://win.rustup.rs/
  - rustup-init.exe -y --default-host %TARGET% --default-toolchain %RUST_VERSION%
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -Vv
  - cargo -V
  #- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  - ps: $vlcdl = 'https://ftp.fau.de/videolan/vlc/3.0.6/win64/vlc-3.0.6-win64.7z'
  - ps: Invoke-WebRequest $vlcdl -OutFile "vlc.7z"
  - ps: $ffmpegdl = 'https://ffmpeg.zeranoe.com/builds/win64/static/ffmpeg-4.1.3-win64-static.zip'
  - ps: Invoke-WebRequest $ffmpegdl -OutFile "ffmpeg.zip"
  - 7z x vlc.7z
  - 7z x ffmpeg.zip

# TODO This is the "test phase", tweak it as you see fit
test_script:
  # we don't run the "test phase" when doing deploys
  - if [%APPVEYOR_REPO_TAG%]==[false] (
      cargo build --release
    )

deploy:
- ps: >-
    $TOKEN = $env:SECURE_GITHUB_TOKEN

    cargo build --release

    if($env:ENABLE_REMOTE_DESKTOP -eq $true) {$blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))}
- cmd: C:\Program Files (x86)\Inno Setup 5\ISCC C:\projects\videoanalysiscontroller\innosetup.iss
- ps: bash deploy.sh VACsetup.exe VACSetup.exe "VideoAnalysisController for Windows" $TOKEN

cache:
  - C:\Users\appveyor\.cargo\registry
  - target

branches:
  only:
    # Release tags
    - /^v\d+\.\d+\.\d+.*$/
    - master

notifications:
  - provider: Email
    on_build_success: false

# Building is done in the test phase, so we disable Appveyor's build phase.
build: false