[package]
name = "rust-vlc"
version = "0.1.0"
authors = ["Oliver Braunsdorf <oliver.braunsdorf@aisec.fraunhofer.de>"]
edition = "2018"
build = "build.rs"

[dependencies]
vlc-rs = { git  = "https://github.com/garkimasera/vlc-rs" }
gilrs = "0.7.1"
