[package]
name = "VideoAnalysisController"
version = "0.1.0"
authors = ["Oliver Braunsdorf <oliver.braunsdorf@aisec.fraunhofer.de>"]
edition = "2018"
build = "build.rs"

[dependencies]
vlc-rs = { path  = "../vlc-rs" }
gilrs = "0.7.1"
#crossterm = "0.9.3"
#glutin = "0.21.0"