TogglePlayPause = "space"
Rewind = "left"
Forward = "right"
IncreaseSpeed = "up"
DecreaseSpeed = "down"
StartLoop = "t"
EndLoop = "z"
BreakLoop = "b"
CutLoop_Offense = "o"
CutLoop_Defense = "d"
CutLoop = "c"
NextMedia = "i"
PreviousMedia = "k"
RestartMedia = "m"
NextClip = "w"
PreviousClip = "s"
RestartClip = "y"
ConcatClips = "u"
Exit = "escape"