on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'enable upterm debugging'     
        required: false
        default: 'false'

name: Continuous integration

jobs:
  Build_and_Test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        rust:
          - 1.53.0  # Minimum Supported Rust Version
            
    steps:
      - uses: actions/checkout@v2

      - name: Install Linux Dependencies
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get -y install libinput-dev libxtst-dev libudev-dev ffmpeg libvlc-dev libx11-dev libxext-dev libxft-dev libxinerama-dev libxcursor-dev libxrender-dev libxfixes-dev libpango1.0-dev libpng-dev libgl1-mesa-dev libglu1-mesa-dev
        
      - name: Install Windows Dependencies
        if: matrix.os == 'windows-latest'
        shell: powershell
        run: |
          nuget install VideoLAN.LibVLC.Windows -Version 3.0.16 -OutputDirectory blubVLCbla

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
          components: rustfmt, clippy

      - name: Manually execute cargo build on Windows
        if: matrix.os == 'windows-latest'
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          set VLC_LIB_DIR=%GITHUB_WORKSPACE%\blubVLCbla\VideoLAN.LibVLC.Windows.3.0.16\build\x64\
          cargo build
          
      
      - uses: actions-rs/cargo@v1
        if: matrix.os != 'windows-latest'
        with:
          command: build

      - uses: actions-rs/cargo@v1
        with:
          command: test

  #    - uses: actions-rs/cargo@v1
  #      with:
  #        command: fmt
  #        args: --all -- --check

      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          
      - name: Setup tmate session
        if: ${{ failure() || github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled == 'true' }}
        uses: mxschmitt/action-tmate@v3
