on: [push, pull_request, workflow_dispatch]

name: Continuous integration

jobs:
  Build_and_Test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        rust:
          - 1.53.0  # Minimum Supported Rust Version
        include:
          - os: windows-latest
            rust_target: x86_64-pc-windows-gnu
            

    steps:
      - name: Install Linux Dependencies
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get -y install libinput-dev libxtst-dev libudev-dev ffmpeg libvlc-dev
        
      - name: Install Windows Dependencies
        if: matrix.os == 'windows-latest'
        shell: powershell
        run: |
          $client = new-object System.Net.WebClient
          $client.DownloadFile("https://ftp.fau.de/videolan/vlc/3.0.6/win64/vlc-3.0.6-win64.7z","vlc.7z")
          7z x vlc.7z
          ls

      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          override: true
          components: rustfmt, clippy

      - uses: actions-rs/cargo@v1
        env: 
          VLC_LIB_DIR: ${{ GITHUB_WORKSPACE }}/vlc-3.0.6/
        with:
          command: build

  #    - uses: actions-rs/cargo@v1
  #      with:
  #        command: test

  #    - uses: actions-rs/cargo@v1
  #      with:
  #        command: fmt
  #        args: --all -- --check

      - uses: actions-rs/cargo@v1
        with:
          command: clippy
